vulnerability_id: CVE-2019-11324
notes:
- links:
  - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11324
  text: The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: 1efadf43dc63317cd9eaa3e0fdb9e05ab07254b1
    repository: https://github.com/urllib3/urllib3
